# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-DOM-BagOfTricks
version:      0.01
version_from: lib/XML/DOM/BagOfTricks.pm
installdirs:  site
requires:
    XML::DOM:                      1.27

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
